# Dự đoán giá chứng khoán

Thư viện

In [74]:
import tensorflow as tf

# I. Dataset

1. Tạo dữ liệu

Sinh ra các điểm từ 0 đến 9 dưới dạng dataset

In [75]:
dataset = tf.data.Dataset.range(10)

In [76]:
# Hiển thị
view = list(dataset.as_numpy_iterator())
view

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Lấy 1 phần tử trong dataset

In [77]:
data_point = dataset.take(1)

In [78]:
# Hiển thị
view = list(data_point.as_numpy_iterator())
view

[0]

Lấy 5 điểm dữ liệu là 1 bản ghi
Sử dụng hàm window:
- size: kích cỡ cửa sổ
- shift: bước nhảy
- drop_remainder: xóa bộ nhớ những cái chưa tạo thành đủ 1 bộ dữ liệu

In [79]:
dataset = dataset.window(size=5, shift=1, drop_remainder=True)

In [80]:
# Hiển thị
for window in dataset:
    for val in window:
        print("{}".format(val.numpy()), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


Biến từng window thành list

In [81]:
dataset = dataset.flat_map(lambda window: window.batch(5))

In [82]:
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


Chia feature và label

In [83]:
dataset =dataset.map(lambda window: (window[:-1],window[-1]))

In [84]:
for window in dataset:
    print(window[0], window[1])

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64) tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64) tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64) tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int64) tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64) tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int64) tf.Tensor(9, shape=(), dtype=int64)
